name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: |
        dir
        dotnet build --configuration Release --no-restore
    - name: Deploy
      run: dotnet publish -r win-x64 -c Release --p:PublishSingleFile=true
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
          # Artifact name
        name: POwerOffTimer-exe-x64
          # Directory containing files to upload
        path: src\PowerOffTimer\bin\Release\netcoreapp3.1\win-x64\publish\PowerOffTimer.exe -p:VersionSuffix="$(git rev-list --count HEAD)
